/**
 * Mock Museum Data for ArtGuard AI Security System
 * Simulates a Louvre-style museum with security infrastructure
 */ 

export const museumData = {
  // Security Cameras
  cameras: [
    {
      id: 1,
      name: "CAM-01 | Salle des États",
      room: "Denon Wing - Room 711",
      wing: "Denon",
      status: "active",
      peopleCount: 145,
      location: { x: 210, y: 50 },
      hasMotionDetection: true,
      lastActivity: "5 seconds ago",
      floorMapKey: "denon-salle-etats",
      featuredArt: ["Mona Lisa", "The Wedding Feast at Cana"]
    },
    {
      id: 2,
      name: "CAM-02 | Daru Staircase",
      room: "Denon Wing - Staircase",
      wing: "Denon",
      status: "active",
      peopleCount: 78,
      location: { x: 150, y: 100 },
      hasMotionDetection: true,
      lastActivity: "10 seconds ago",
      floorMapKey: "denon-daru-stairs",
      featuredArt: ["Winged Victory of Samothrace"]
    },
    {
      id: 3,
      name: "CAM-03 | Egyptian Antiquities",
      room: "Sully Wing - Ground Floor",
      wing: "Sully",
      status: "active",
      peopleCount: 42,
      location: { x: 175, y: 100 },
      hasMotionDetection: true,
      lastActivity: "15 seconds ago",
      floorMapKey: "sully-egyptian",
      featuredArt: ["Great Sphinx", "Egyptian Sarcophagi", "Seated Scribe"]
    },
    {
      id: 4,
      name: "CAM-04 | Cour Marly",
      room: "Richelieu Wing - Room 105",
      wing: "Richelieu",
      status: "active",
      peopleCount: 35,
      location: { x: 150, y: 150 },
      hasMotionDetection: true,
      lastActivity: "8 seconds ago",
      floorMapKey: "richelieu-marly",
      featuredArt: ["Marly Horses", "French Sculptures"]
    },
    {
      id: 5,
      name: "CAM-05 | Sculpture Garden",
      room: "Outdoor Plaza",
      status: "active",
      peopleCount: 8,
      location: { x: 150, y: 200 },
      hasMotionDetection: true,
      lastActivity: "2 minutes ago",
      floorMapKey: "sculptureHall"
    },
    {
      id: 6,
      name: "CAM-06 | Crown Jewels Vault",
      room: "High Security Vault",
      status: "active",
      peopleCount: 2,
      location: { x: 250, y: 50 },
      hasMotionDetection: true,
      lastActivity: "10 seconds ago",
      floorMapKey: "securityOffice"
    }
  ],

  // Security Guards
  guards: [
    {
      id: 1,
      name: "Agent Dubois",
      location: "Salle des États - Mona Lisa",
      room: "Denon Wing - Room 711",
      wing: "Denon",
      status: "on-duty",
      lastCheckIn: "1 minute ago",
      position: { x: 210, y: 50 },
      badge: "LOU-001",
      yearsExperience: 12
    },
    {
      id: 2,
      name: "Agent Moreau",
      location: "Daru Staircase",
      room: "Denon Wing - Staircase",
      wing: "Denon",
      status: "on-duty",
      lastCheckIn: "3 minutes ago",
      position: { x: 150, y: 100 },
      badge: "LOU-002",
      yearsExperience: 7
    },
    {
      id: 3,
      name: "Agent Laurent",
      location: "Egyptian Antiquities",
      room: "Sully Wing - Ground Floor",
      wing: "Sully",
      status: "on-duty",
      lastCheckIn: "2 minutes ago",
      position: { x: 175, y: 100 },
      badge: "LOU-003",
      yearsExperience: 9
    },
    {
      id: 4,
      name: "Agent Rousseau",
      location: "Cour Marly",
      room: "Richelieu Wing - Room 105",
      wing: "Richelieu",
      status: "on-duty",
      lastCheckIn: "4 minutes ago",
      position: { x: 150, y: 150 },
      badge: "LOU-004",
      yearsExperience: 15
    }
  ],

  // Active Security Alerts
  alerts: [
    {
      id: 1,
      severity: "medium",
      type: "motion",
      message: "Large crowd detected near Mona Lisa protective case",
      location: "Denon Wing - Salle des États",
      camera: 1,
      timestamp: "3 minutes ago",
      status: "monitoring",
      autoGenerated: true
    }
  ],

  // Museum Rooms/Galleries
  rooms: [
    {
      id: 1,
      name: "Main Lobby",
      visitorCount: 45,
      capacity: 100,
      threatLevel: "low",
      cameras: [1],
      guards: [1],
      status: "open",
      valuableArtworks: 0
    },
    {
      id: 2,
      name: "Gallery 3 - Renaissance Paintings",
      visitorCount: 32,
      capacity: 50,
      threatLevel: "medium",
      cameras: [2],
      guards: [2],
      status: "open",
      valuableArtworks: 12,
      featuredArt: ["Mona Lisa", "The Wedding at Cana"]
    },
    {
      id: 3,
      name: "Gallery 7 - Egyptian Antiquities",
      visitorCount: 18,
      capacity: 40,
      threatLevel: "low",
      cameras: [3],
      guards: [],
      status: "open",
      valuableArtworks: 24
    },
    {
      id: 4,
      name: "High Security Vault",
      visitorCount: 0,
      capacity: 10,
      threatLevel: "high",
      cameras: [6],
      guards: [4],
      status: "restricted",
      valuableArtworks: 8,
      featuredArt: ["Crown Jewels of France", "Regent Diamond"]
    },
    {
      id: 5,
      name: "Sculpture Garden",
      visitorCount: 22,
      capacity: 80,
      threatLevel: "low",
      cameras: [5],
      guards: [],
      status: "open",
      valuableArtworks: 6
    },
    {
      id: 6,
      name: "Loading Dock",
      visitorCount: 0,
      capacity: 20,
      threatLevel: "low",
      cameras: [4],
      guards: [],
      status: "service",
      valuableArtworks: 0
    }
  ],

  // System Status
  system: {
    status: "operational",
    uptime: "99.8%",
    lastMaintenance: "3 days ago",
    totalCameras: 6,
    activeCameras: 5,
    totalGuards: 4,
    onDutyGuards: 3,
    totalAlerts: 3,
    criticalAlerts: 1,
    currentThreatLevel: "medium"
  },

  // Recent Activity Log (for status reports)
  recentActivity: [
    {
      id: 1,
      time: "30 seconds ago",
      type: "alert",
      message: "Access attempt detected - Crown Jewels Vault",
      severity: "high"
    },
    {
      id: 2,
      time: "1 minute ago",
      type: "guard",
      message: "Guard Chen checked in at Gallery 3",
      severity: "info"
    },
    {
      id: 3,
      time: "2 minutes ago",
      type: "camera",
      message: "Motion pattern analyzed - Gallery 3",
      severity: "medium"
    },
    {
      id: 4,
      time: "2 minutes ago",
      type: "guard",
      message: "Guard Martinez checked in at Main Entrance",
      severity: "info"
    },
    {
      id: 5,
      time: "8 minutes ago",
      type: "guard",
      message: "Guard Johnson started break",
      severity: "info"
    }
  ]
};

// Helper functions
export const getCameraById = (id: number) => {
  return museumData.cameras.find(camera => camera.id === id);
};

export const getGuardByName = (name: string) => {
  return museumData.guards.find(guard => 
    guard.name.toLowerCase().includes(name.toLowerCase())
  );
};

export const getAlertsBySeverity = (severity: string) => {
  return museumData.alerts.filter(alert => alert.severity === severity);
};

export const getRoomByName = (name: string) => {
  return museumData.rooms.find(room => 
    room.name.toLowerCase().includes(name.toLowerCase())
  );
};

export default museumData;
